pdf:
	pandoc report.md -V geometry:margin=1in --latex-engine=xelatex --highlight-style pygments -o output/report.pdf

extra:
	pandoc extra.md -V geometry:margin=1in --latex-engine=xelatex --highlight-style pygments -o extra/report.pdf
